-- SQLite, local single-user store for settings and workspaces.
-- Frames and signal samples are NOT stored here (ring buffer + log files).
-- Times are UTC ISO-8601 text. Ids are random uuid text generated by the app.

pragma foreign_keys = on;

create table if not exists channels (
  id text primary key,
  name text not null unique,
  interface text not null,                -- python-can interface: socketcan, pcan, slcan, virtual, ...
  channel text not null,                  -- adapter channel string
  bitrate integer not null check (bitrate > 0),
  fd_enabled integer not null default 0 check (fd_enabled in (0,1)),
  fd_data_bitrate integer check (fd_data_bitrate is null or fd_data_bitrate > 0),
  listen_only integer not null default 1 check (listen_only in (0,1)),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists databases (
  id text primary key,
  channel_id text not null references channels(id) on delete cascade,
  path text not null,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  unique (channel_id, path)
);
create index if not exists databases_channel_idx on databases (channel_id);

create table if not exists filters (
  id text primary key,
  channel_id text references channels(id) on delete cascade,  -- null = all channels
  mode text not null check (mode in ('pass','stop')),
  id_from integer not null,
  id_to integer not null,
  is_extended integer not null default 0 check (is_extended in (0,1)),
  direction text not null default 'both' check (direction in ('rx','tx','both')),
  enabled integer not null default 1 check (enabled in (0,1)),
  check (id_to >= id_from)
);
create index if not exists filters_channel_idx on filters (channel_id);

create table if not exists generator_frames (
  id text primary key,
  channel_id text not null references channels(id) on delete cascade,
  can_id integer not null,
  is_extended integer not null default 0 check (is_extended in (0,1)),
  is_fd integer not null default 0 check (is_fd in (0,1)),
  data blob not null,
  period_ms integer check (period_ms is null or period_ms >= 1),  -- null = send once on demand
  enabled integer not null default 1 check (enabled in (0,1)),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index if not exists generator_channel_idx on generator_frames (channel_id);

create table if not exists log_sessions (
  id text primary key,
  path text not null,
  format text not null check (format in ('asc','blf')),
  started_at text not null,
  stopped_at text,
  frame_count integer not null default 0,
  check (stopped_at is null or stopped_at >= started_at)
);
create index if not exists log_sessions_started_idx on log_sessions (started_at);

create table if not exists workspaces (
  id text primary key,
  name text not null unique,
  layout_json text not null default '{}',   -- pane positions, trace columns, graph signals
  updated_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists settings (
  key text primary key,
  value text not null                        -- e.g. mcp.enabled, mcp.port, mcp.allow_transmit, mcp.tools_enabled, ring_buffer_size
);
-- The bearer token is a user-only file (token) in the data directory, not in this table.
